version: '3'

services:

  db:
    image: mysql:5.7
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=laraveldb
      - MYSQL_USER=laravel
      - MYSQL_PASSWORD=password
    ports:
      - "3306:3306"

  #app1
  php1:
    build:
      context: app
      dockerfile: Dockerfile
    restart: always
    ports:
      - "5000:80"
    volumes:
      - ./code:/var/www/html
    environment:
      - DB_HOST=db
    depends_on:
      - db
    links:
      - db
  
  #app2
  php2:
    build:
      context: app
      dockerfile: Dockerfile
    restart: always
    ports:
      - "6000:80"
    volumes:
      - ./code:/var/www/html
    environment:
      - DB_HOST=db
    depends_on:
      - db
    links:
      - db

  #nginx1
  nginx1:
    build:
      context: nginx
      dockerfile: Dockerfile
    restart: always
    ports:
      - "8080:80"
    volumes:
      - ./nginx1.conf:/etc/nginx/nginx.conf
      - ./code:/var/www/html
    links:
      - php1

  #nginx2
  nginx2:
    build:
      context: nginx
      dockerfile: Dockerfile
    restart: always
    ports:
      - "8082:80"
    volumes:
      - ./nginx2.conf:/etc/nginx/nginx.conf
      - ./code:/var/www/html
    links:
      - php2

  #phpmyadmin
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    restart: always
    environment:
    - PMA_HOST=db
    - PMA_USER=laravel
    - PMA_PASSWORD=password
    - PMA_ARBITRARY=1

volumes:
  mysql_data: {}
