version: '3'

services:

  #mysql
  db:
    image: mysql:5.7
    container_name: db
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=laraveldb
      - MYSQL_USER=laravel
      - MYSQL_PASSWORD=password
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - app_network

  #app1
  php1:
    build:
      context: ./app1
      dockerfile: Dockerfile
    container_name: php1
    volumes:
      - ./app1:/var/www/html
    environment:
      - DB_HOST=db
    ports : 
      - 9000
    depends_on:
      - db
    networks:
      - app_network
  
  #app2
  php2:
    build:
      context: ./app2
      dockerfile: Dockerfile
    container_name: php2
    volumes:
      - ./app2:/var/www/html
    ports : 
      - 9000
    environment:
      - DB_HOST=db
    networks:
      - app_network

  #nginx1
  nginx1:
    image: nginx:alpine
    container_name: nginx1
    ports:
      - "8081:80"
    volumes:
      - ./nginx/nginx1.conf:/etc/nginx/conf.d/default.conf
      - ./app1:/var/www/html
    networks:
      - app_network
  
  #nginx2
  nginx2:
    image: nginx:alpine
    container_name: nginx2
    ports:
      - "8082:80"
    volumes:
      - ./nginx/nginx2.conf:/etc/nginx/conf.d/default.conf
      - ./app2:/var/www/html
    networks:
      - app_network

  #phpmyadmin
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    restart: always
    ports:
      - 8083:80
    environment:
    - PMA_HOST=db
    - PMA_USER=laravel
    - PMA_PASSWORD=password
    - PMA_ARBITRARY=1
    networks:
      - app_network
  
networks:
  app_network:
    driver: bridge

volumes:
    mysql_data: {}
