version: '3'

services:
  # MySQL
  db:
    image: mysql:5.7
    container_name: db
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: laraveldb
      MYSQL_USER: laravel
      MYSQL_PASSWORD: password
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - app_network

  # App1 - PHP
  php1:
    build:
      context: ./
      dockerfile: Dockerfile
    container_name: php1
    volumes:
      - ./:/var/www/html
      - ./install.sh:/usr/local/bin/install.sh
    environment:
      - RUN_MIGRATIONS=true
      - DB_HOST=db
      - SERVER_NOM=Serveur 1
    depends_on:
      - db
    networks:
      - app_network
    command: ["/bin/sh", "/usr/local/bin/install.sh"]
    expose:
    - 9000
  
  # App2 - PHP
  php2:
    build:
      context: ./
      dockerfile: Dockerfile
    container_name: php2
    volumes:
      - ./:/var/www/html
      - ./install.sh:/usr/local/bin/install.sh
    environment:
      - DB_HOST=db
      - SERVER_NOM=Serveur 2
    depends_on:
      - db
    networks:
      - app_network
    command: ["/bin/sh", "/usr/local/bin/install.sh"]
    expose:
    - 9000

  # Nginx1
  nginx1:
    image: nginx:alpine
    container_name: nginx1
    ports:
      - "8081:80"
    volumes:
      - ./nginx/nginx1.conf:/etc/nginx/conf.d/default.conf
      - ./:/var/www/html
    networks:
      - app_network
  
  # Nginx2
  nginx2:
    image: nginx:alpine
    container_name: nginx2
    ports:
      - "8082:80"
    volumes:
      - ./nginx/nginx2.conf:/etc/nginx/conf.d/default.conf
      - ./:/var/www/html
    networks:
      - app_network

  # phpMyAdmin
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    restart: always
    ports:
      - "8083:80"
    environment:
      PMA_HOST: db
      PMA_USER: laravel
      PMA_PASSWORD: password
      PMA_ARBITRARY: 1
    networks:
      - app_network

networks:
  app_network: {}

volumes:
  mysql_data: {}
